import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
	players: defineTable({
		userId: v.string(),
		displayName: v.optional(v.string()),
		credits: v.number(),
		pitySr: v.number(),
		pityUr: v.number(),
		totalPulls: v.number(),
		owned: v.record(
			v.string(),
			v.object({
				count: v.number(),
				firstAcquired: v.number(),
			}),
		),
		characterAcquired: v.boolean(),
		lastStipendDate: v.union(v.string(), v.null()),
		streak: v.number(),
		achievements: v.record(v.string(), v.number()),
		minedToday: v.optional(v.number()),
		minedDate: v.optional(v.string()),
		contactRewarded: v.optional(v.boolean()),
		dailyDate: v.optional(v.string()),
		dailyCipher: v.optional(v.boolean()),
		dailyRecall: v.optional(v.boolean()),
		dailyScanned: v.optional(v.array(v.string())),
		createdAt: v.number(),
		updatedAt: v.number(),
	}).index("by_userId", ["userId"]),
	messages: defineTable({
		userId: v.string(),
		name: v.string(),
		email: v.string(),
		message: v.string(),
		rewardGranted: v.boolean(),
		createdAt: v.number(),
	}).index("by_userId", ["userId"]),
	cards: defineTable({
		cardId: v.string(),
		name: v.string(),
		type: v.union(
			v.literal("CHARACTER"),
			v.literal("ROLE"),
			v.literal("PROJECT"),
			v.literal("SKILL"),
		),
		rarity: v.union(
			v.literal("UR"),
			v.literal("SSR"),
			v.literal("SR"),
			v.literal("R"),
			v.literal("C"),
		),
		weight: v.number(),
		active: v.boolean(),
		tagline: v.string(),
		description: v.string(),
		details: v.array(v.string()),
		tags: v.array(v.string()),
		links: v.array(v.object({ label: v.string(), href: v.string() })),
		note: v.optional(v.string()),
		createdAt: v.optional(v.number()),
	}).index("by_cardId", ["cardId"]),
});
